config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/demichie/OpenPDAC-13:
      branch: main
      repo: https://github.com/demichie/OpenPDAC-13/
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/demichie/OpenPDAC-13 git:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-salmon-cow.sh
        container: qc.acc_woozy-coral-catfish
  QC.Doc:
    repos:
      github.com/demichie/OpenPDAC-13 find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-yellow-horse.sh
        container: qc.doc_crappy-puce-giraffe
      github.com/demichie/OpenPDAC-13 git:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-asparagus-dog.sh
        container: qc.doc_hilly-silver-dragon
      github.com/demichie/OpenPDAC-13 markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-chocolate-barnacle.sh
        container: qc.doc_skanky-scarlet-dormouse
  QC.Lic:
    repos:
      github.com/demichie/OpenPDAC-13 licensee:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-crimson-dodo.sh
        container: qc.lic_tacky-purple-mole
  QC.Met:
    repos:
      github.com/demichie/OpenPDAC-13 cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-indigo-squirrel.sh
        container: qc.met_scaly-chartreuse-okapi
  QC.Sec:
    repos:
      github.com/demichie/OpenPDAC-13 bandit:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-denim-fousek.sh
        container: qc.sec_queasy-zucchini-bandicoot
  QC.Sty:
    repos:
      github.com/demichie/OpenPDAC-13 flake8:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-cerulean-dane.sh
        container: qc.sty_cranky-carmine-sponge
  QC.Uni:
    repos:
      github.com/demichie/OpenPDAC-13 pytest:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-pink-crocodile.sh
        container: qc.uni_whiny-mustard-donkey
  QC.Ver:
    repos:
      github.com/demichie/OpenPDAC-13 get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-charcoal-reindeer.sh
        container: qc.ver_squeaky-lime-stoat
timeout: 5400
