config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/demichie/OpenPDAC-13:
      branch: main
      repo: https://github.com/demichie/OpenPDAC-13
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/demichie/OpenPDAC-13 git:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-khaki-giraffe.sh
        container: qc.acc_boozy-wheat-spoonbill
  QC.Doc:
    repos:
      github.com/demichie/OpenPDAC-13 find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.beady-azure-harrier.sh
        container: qc.doc_queasy-bistre-cuttlefish
      github.com/demichie/OpenPDAC-13 git:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-orange-swan.sh
        container: qc.doc_cranky-viridian-tzu
      github.com/demichie/OpenPDAC-13 markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-brown-rat.sh
        container: qc.doc_hazy-sangria-baboon
  QC.Lic:
    repos:
      github.com/demichie/OpenPDAC-13 licensee:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-khaki-centipede.sh
        container: qc.lic_flaky-cerise-rhinoceros
  QC.Met:
    repos:
      github.com/demichie/OpenPDAC-13 cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-thistle-bat.sh
        container: qc.met_crappy-indigo-burmese
  QC.Sec:
    repos:
      github.com/demichie/OpenPDAC-13 bandit:
        commands:
        - /usr/bin/env sh .sqa/script.randy-firebrick-koala.sh
        container: qc.sec_snoopy-lavender-octopus
  QC.Sty:
    repos:
      github.com/demichie/OpenPDAC-13 flake8:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-ultramarine-penguin.sh
        container: qc.sty_snazzy-cardinal-tiger
  QC.Uni:
    repos:
      github.com/demichie/OpenPDAC-13 pytest:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-olive-lizard.sh
        container: qc.uni_chewy-carmine-maltese
  QC.Ver:
    repos:
      github.com/demichie/OpenPDAC-13 get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-myrtle-bison.sh
        container: qc.ver_lovely-jade-turkey
timeout: 5400
